spd = 2;
xspd = 0;
yspd = 0;
COLLISION = false;
x_frame = 0;
y_frame = 11;
x_offset = sprite_get_xoffset(mask_index);
y_offset = sprite_get_yoffset(mask_index);
//s_base = s_f_base_light;
s_shirt = s_m_shirt_longsleeve_teal;
s_legs = s_m_legs_pants_white;
s_feet = s_m_feet_shoes_black;
s_eyes = s_m_eyes_default;
s_nose = s_m_nose_default;
s_ears = s_m_ears_elven_light;
s_hair = s_m_hair_bangs_brown;
base_gender = 0;
base_skin = 0;
shirt_option = 0;
//s_base = array_create([2,10], [s_m_base_dark,s_m_base_dark2,s_m_base_darkelf,s_m_base_darkelf2,s_m_base_light,s_m_base_orc,s_m_base_redorc,s_m_base_skeleton,s_m_base_tanned,s_m_base_tanned2],[s_m_base_dark,s_m_base_dark2,s_m_base_darkelf,s_m_base_darkelf2,s_m_base_light,s_m_base_orc,s_m_base_redorc,s_m_base_skeleton,s_m_base_tanned,s_m_base_tanned2]);
for (var i = 0; i < 2; i++)
	for (var j = 0; j < 10; j++)
		s_base[i,j] = s_player_mask;
for (var i = 0; i < 10; i++)
	for (var j = 0; j < 3; j++)
	{
		s_f_ears[i,j] = s_f_ears_default;
		s_m_ears[i,j] = s_m_ears_default;
		s_f_eyes[i,j] = s_f_eyes_default;
		s_m_eyes[i,j] = s_m_eyes_default;
		s_f_nose[i,j] = s_f_nose_default;
		s_m_nose[i,j] = s_m_nose_default;
	}
		
s_base[0,0] = s_m_base_dark;
s_base[0,1] = s_m_base_dark2;
s_base[0,2] = s_m_base_darkelf;
s_base[0,3] = s_m_base_darkelf2;
s_base[0,4] = s_m_base_light;
s_base[0,5] = s_m_base_orc;
s_base[0,6] = s_m_base_redorc;
s_base[0,7] = s_m_base_skeleton;
s_base[0,8] = s_m_base_tanned;
s_base[0,9] = s_m_base_tanned2;
s_base[1,0] = s_f_base_dark;
s_base[1,1] = s_f_base_dark2;
s_base[1,2] = s_f_base_darkelf;
s_base[1,3] = s_f_base_darkelf2;
s_base[1,4] = s_f_base_light;
s_base[1,5] = s_f_base_orc;
s_base[1,6] = s_f_base_redorc;
s_base[1,7] = s_f_base_skeleton;
s_base[1,8] = s_f_base_tanned;
s_base[1,9] = s_f_base_tanned2;